export const spots = [
  {
    "id": 1,
    "name": "호암산과 호압사",
    "name_en": "Hoamsan & Hoabsa Temple",
    "name_zh": "虎岩山与虎压寺",
    "name_ja": "虎岩山とホアプサ寺",
    "image": "/spot1.jpg",
    "categories": ["자연·산책", "역사·문화"],
    "categories_en": ["Nature", "History"],
    "categories_zh": ["自然·散步", "历史·文化"],
    "categories_ja": ["自然・散策", "歴史・文化"],
    "recommendFor": ["혼자", "연인", "가족"],
    "address": "금천구 호암로 278",
    "address_en": "278 Hoam-ro, Geumcheon-gu",
    "address_zh": "衿川区虎岩路278",
    "address_ja": "衿川区虎岩路278",
    "hours": "24시간 (호암산) / 일출~일몰 (호압사)",
    "hours_en": "24 hours (Hoamsan) / Sunrise to Sunset (Hoabsa)",
    "hours_zh": "24小时 (虎岩山) / 日出~日落 (虎压寺)",
    "hours_ja": "24時間 (虎岩山) / 日の出〜日没 (ホアプサ)",
    "fee": "무료",
    "fee_en": "Free",
    "fee_zh": "免费",
    "fee_ja": "無料",
    "transit": "마을버스 금천01 (독산역·금천구청역 → 호압사 입구)",
    "transit_en": "Village Bus Geumcheon 01 (Doksan/Geumcheon-gu Office Stn → Hoabsa Entrance)",
    "transit_zh": "社区巴士 衿川01 (秃山站·衿川区厅站 → 虎压寺入口)",
    "transit_ja": "マウルバス 衿川01 (禿山駅・衿川区庁駅 → ホアプサ入口)",
    "duration": "반나절 (3~4시간)",
    "duration_en": "Half day (3~4 hours)",
    "duration_zh": "半天 (3~4小时)",
    "duration_ja": "半日 (3〜4時間)",
    "highlights": ["호암산성(국가지정문화유산)","석조약사여래좌상(서울시 유형문화유산)","칼바위","호암늘솔길","호압사","바라밀공원(사찰림 산림여가공간)"],
    "highlights_en": ["Hoamsanseong Fortress", "Stone Seated Bhaisajyaguru Buddha", "Kalbawi Rock", "Hoam Neulsol-gil Trail", "Hoabsa Temple", "Baramil Park"],
    "highlights_zh": ["虎岩山城", "石造药师如来坐像", "刀岩", "虎岩松道", "虎压寺", "波罗蜜公园"],
    "highlights_ja": ["虎岩山城", "石造薬師如来坐像", "カルバウィ(刃岩)", "虎岩ヌルソル道", "ホアプサ(虎圧寺)", "パラミル公園"],
    "story": "태조 이성계가 한양 궁궐을 무너뜨리는 호랑이 형상의 산을 누르기 위해 절을 지어 '호압사(虎壓寺)'라 명명했다는 전설이 전해진다.",
    "story_en": "Legend says that King Taejo built this temple to suppress the tiger-shaped energy of the mountain that threatened the capital, naming it Hoabsa (Tiger Suppressing Temple).",
    "story_zh": "传说太祖李成桂为了镇压威胁汉阳宫殿的虎形山势而建造了寺庙，并命名为“虎压寺”。",
    "story_ja": "太祖李成桂が、漢陽の王宮を脅かす虎の形をした山の気を抑えるために寺を建て、「虎圧寺(ホアプサ)」と命名したという伝説が伝わっています。",
    "lat": 37.452615,
    "lng": 126.925542
  },
  {
    "id": 2,
    "name": "안양천(벚꽃길)",
    "name_en": "Anyangcheon Cherry Blossom Trail",
    "name_zh": "安养川樱花路",
    "name_ja": "安養川桜並木道",
    "image": "/spot2.jpg",
    "categories": ["자연·산책", "야경"],
    "categories_en": ["Nature", "Night View"],
    "categories_zh": ["自然·散步", "夜景"],
    "categories_ja": ["自然・散策", "夜景"],
    "recommendFor": ["혼자", "친구", "연인", "가족"],
    "address": "안양천 금천구 구간 (가산디지털단지역 ~ 금천구청역, 약 4km)",
    "address_en": "Anyangcheon Geumcheon Section (Gasan Digital Complex Stn ~ Geumcheon-gu Office Stn)",
    "address_zh": "安养川 衿川区路段 (加山数码团地站 ~ 衿川区厅站)",
    "address_ja": "安養川 衿川区区間 (加山デジタル団地駅 〜 衿川区庁駅)",
    "hours": "24시간",
    "hours_en": "24 hours",
    "hours_zh": "24小时",
    "hours_ja": "24時間",
    "fee": "무료",
    "fee_en": "Free",
    "fee_zh": "免费",
    "fee_ja": "無料",
    "transit": "1호선 금천구청역 도보 5분",
    "transit_en": "Line 1 Geumcheon-gu Office Stn, 5 min walk",
    "transit_zh": "1号线 衿川区厅站 步行5分钟",
    "transit_ja": "1号線 衿川区庁駅 徒歩5分",
    "duration": "1~2시간",
    "duration_en": "1~2 hours",
    "duration_zh": "1~2小时",
    "duration_ja": "1〜2時間",
    "highlights": ["벚꽃십리길 (4km)","장미원","금천한내교 야경"],
    "highlights_en": ["4km Cherry Blossom Trail", "Rose Garden", "Geumcheon Hannaegyo Bridge Night View"],
    "highlights_zh": ["樱花十里路 (4km)", "玫瑰园", "衿川汉内桥夜景"],
    "highlights_ja": ["桜十里道 (4km)", "バラ園", "衿川ハンネ橋の夜景"],
    "story": "금천구청역에서 가산디지털단지역까지 약 4km에 걸쳐 이어지는 '벚꽃십리길'. 봄에는 벚꽃, 초여름엔 장미원, 밤에는 금천한내교 야경까지 계절마다 다른 매력을 선사한다.",
    "story_en": "The '10-ri Cherry Blossom Trail' stretches about 4km from Geumcheon-gu Office Station to Gasan Digital Complex Station. It offers different charms every season.",
    "story_zh": "从衿川区厅站到加山数码团地站延伸约4公里的“樱花十里路”。春天有樱花，初夏有玫瑰园，夜晚有衿川汉内桥夜景，每个季节都有不同的魅力。",
    "story_ja": "衿川区庁駅から加山デジタル団地駅まで約4kmにわたって続く「桜十里道」。春には桜、初夏にはバラ園、夜には衿川ハンネ橋の夜景まで、季節ごとに異なる魅力を提供します。",
    "lat": 37.455827,
    "lng": 126.893040
  },
  {
    "id": 3,
    "name": "오미생태공원",
    "name_en": "Omi Ecological Park",
    "name_zh": "五味生态公园",
    "name_ja": "五味生態公園",
    "image": "/spot3.jpg",
    "categories": ["자연·산책", "체험·교육"],
    "categories_en": ["Nature", "Education"],
    "categories_zh": ["自然·散步", "体验·教育"],
    "categories_ja": ["自然・散策", "体験・教育"],
    "recommendFor": ["가족", "혼자"],
    "address": "금천구 시흥계곡 일대 (호암산 자락)",
    "address_en": "Siheung Valley area, Geumcheon-gu (Foot of Hoamsan)",
    "address_zh": "衿川区 始兴溪谷一带 (虎岩山脚下)",
    "address_ja": "衿川区 始興渓谷一帯 (虎岩山のふもと)",
    "hours": "24시간",
    "hours_en": "24 hours",
    "hours_zh": "24小时",
    "hours_ja": "24時間",
    "fee": "무료",
    "fee_en": "Free",
    "fee_zh": "免费",
    "fee_ja": "無料",
    "transit": "마을버스 금천01",
    "transit_en": "Village Bus Geumcheon 01",
    "transit_zh": "社区巴士 衿川01",
    "transit_ja": "マウルバス 衿川01",
    "duration": "1~2시간",
    "duration_en": "1~2 hours",
    "duration_zh": "1~2小时",
    "duration_ja": "1〜2時間",
    "highlights": ["5개 테마 정원","다양한 식물 관찰","자연 휴식 공간"],
    "highlights_en": ["5 Theme Gardens", "Diverse Plant Observation", "Natural Relaxation Space"],
    "highlights_zh": ["5个主题花园", "多种植物观察", "自然休憩空间"],
    "highlights_ja": ["5つのテーマガーデン", "多様な植物観察", "自然の休息空間"],
    "story": "호암산 자락 시흥계곡에 조성된 생태공원. 구역마다 다른 주제의 정원이 펼쳐져 계절마다 다채로운 식물을 만날 수 있다.",
    "story_en": "An ecological park built in Siheung Valley at the foot of Hoamsan Mountain. Different themed gardens unfold in each area, allowing you to meet various plants every season.",
    "story_zh": "位于虎岩山脚下始兴溪谷的生态公园。每个区域都有不同主题的花园，每个季节都能见到丰富多彩的植物。",
    "story_ja": "虎岩山のふもと、始興渓谷に造成された生態公園。区域ごとに異なるテーマの庭園が広がり、季節ごとに多彩な植物に出会うことができます。",
    "lat": 37.446328,
    "lng": 126.909762
  },
  {
    "id": 4,
    "name": "금천체육공원 전망대",
    "name_en": "Geumcheon Sports Park Observatory",
    "name_zh": "金川体育公园观景台",
    "name_ja": "金川体育公園展望台",
    "image": "/spot4.jpg",
    "categories": ["자연·산책", "야경"],
    "categories_en": ["Nature", "Night View"],
    "categories_zh": ["自然·散步", "夜景"],
    "categories_ja": ["自然・散策", "夜景"],
    "recommendFor": ["친구", "혼자"],
    "address": "금천구 독산동",
    "address_en": "Doksan-dong, Geumcheon-gu",
    "address_zh": "衿川区 秃山洞",
    "address_ja": "衿川区 禿山洞",
    "hours": "24시간",
    "hours_en": "24 hours",
    "hours_zh": "24小时",
    "hours_ja": "24時間",
    "fee": "무료",
    "fee_en": "Free",
    "fee_zh": "免费",
    "fee_ja": "無料",
    "transit": "인근 버스 이용",
    "transit_en": "Use nearby buses",
    "transit_zh": "利用附近巴士",
    "transit_ja": "近隣のバスを利用",
    "duration": "1~2시간",
    "duration_en": "1~2 hours",
    "duration_zh": "1~2小时",
    "duration_ja": "1〜2時間",
    "highlights": ["음악 테마 산책길","전망대","도심 야경","다양한 조형물"],
    "highlights_en": ["Music-themed Trail", "Observatory", "City Night View", "Various Sculptures"],
    "highlights_zh": ["音乐主题散步道", "观景台", "城市夜景", "多种雕塑"],
    "highlights_ja": ["音楽テーマの散策路", "展望台", "都心の夜景", "多様な造形物"],
    "story": "음악을 주제로 조성된 산책길과 전망대. 낮에는 주변 녹음과 풍경을, 밤에는 화려한 도심 야경과 조명을 감상할 수 있다.",
    "story_en": "A trail and observatory created with a music theme. You can enjoy the surrounding greenery and scenery during the day, and the brilliant city night view and lights at night.",
    "story_zh": "以音乐为主题打造的散步道和观景台。白天可以欣赏周边的绿意和风景，夜晚可以欣赏华丽的城市夜景和灯光。",
    "story_ja": "音楽をテーマに造成された散策路と展望台。昼間は周囲の緑と風景を、夜は華やかな都心の夜景と照明を鑑賞できます。",
    "lat": 37.468438,
    "lng": 126.908497
  },
  {
    "id": 5,
    "name": "금천G밸리와 순이의 집",
    "name_en": "G-Valley & Sooni's House",
    "name_zh": "金川G谷与顺伊之家",
    "name_ja": "G-バレーとスニの家",
    "image": "/spot5.jpg",
    "categories": ["역사·문화", "체험·교육"],
    "categories_en": ["History", "Education"],
    "categories_zh": ["历史·文化", "体验·教育"],
    "categories_ja": ["歴史・文化", "体験・教育"],
    "recommendFor": ["친구", "가족"],
    "address": "금천구 벚꽃로44길 17 (순이의 집)",
    "address_en": "17 Beotkkot-ro 44-gil, Geumcheon-gu (Sooni's House)",
    "address_zh": "衿川区 樱花路44路 17 (顺伊之家)",
    "address_ja": "衿川区 桜路44ギル 17 (スニの家)",
    "hours": "월~토 10:00~17:00 (입장 16:30까지) / 일요일 휴무",
    "hours_en": "Mon-Sat 10:00-17:00 (Last entry 16:30) / Closed Sundays",
    "hours_zh": "周一~周六 10:00~17:00 (16:30截止入场) / 周日休息",
    "hours_ja": "月〜土 10:00〜17:00 (入場は16:30まで) / 日曜定休",
    "closed_note": "일요일 휴무",
    "fee": "무료",
    "fee_en": "Free",
    "fee_zh": "免费",
    "fee_ja": "無料",
    "transit": "1·7호선 가산디지털단지역 2번출구 도보 5분",
    "transit_en": "Line 1/7 Gasan Digital Complex Stn Exit 2, 5 min walk",
    "transit_zh": "1·7号线 加山数码团地站 2号出口 步行5分钟",
    "transit_ja": "1・7号線 加山デジタル団地駅 2番出口 徒歩5分",
    "duration": "1~2시간",
    "duration_en": "1~2 hours",
    "duration_zh": "1~2小时",
    "duration_ja": "1〜2時間",
    "highlights": ["쪽방체험관 (6개 테마방)","가리봉상회 (1980년대 슈퍼마켓 재현)","기획전시관","2층 영상관","서울미래유산 지정 건물"],
    "highlights_en": ["Tiny Room Experience (6 rooms)", "Garibong Store (1980s supermarket)", "Special Exhibition Hall", "2nd Floor Video Room", "Seoul Future Heritage"],
    "highlights_zh": ["小房体验馆 (6个主题房)", "加里峰商会 (重现1980年代超市)", "策划展示馆", "2楼影像馆", "首尔未来遗产指定建筑"],
    "highlights_ja": ["チョッパン(小部屋)体験館 (6つのテーマ)", "カリボン商会 (1980年代のスーパー再現)", "企画展示館", "2階映像館", "ソウル未来遺産指定建物"],
    "story": "1960~90년대 구로공단 여성 노동자들의 삶을 재현한 체험관. 1985년 건립 주택을 2013년 전시관으로 개관, 2014년 서울미래유산으로 지정됐다.",
    "story_en": "A museum reproducing the lives of female workers in the Guro Industrial Complex from the 1960s to 90s. Opened in 2013 and designated as Seoul Future Heritage in 2014.",
    "story_zh": "重现1960~90年代九老工团女工生活的体验馆。2013年将1985年建造的住宅改建为展示馆开馆，2014年被指定为首尔未来遗产。",
    "story_ja": "1960〜90年代の九老工団の女性労働者たちの生を再現した体験館。1985年建立の住宅を2013年に展示館として開館、2014年にソウル未来遺産に指定されました。",
    "lat": 37.482788,
    "lng": 126.883624
  },
  {
    "id": 6,
    "name": "시흥행궁전시관과 은행나무",
    "name_en": "Siheung Haenggung Exhibition Hall",
    "name_zh": "始兴行宫展示馆与银杏树",
    "name_ja": "始興行宮展示館と銀杏の木",
    "image": "/spot6.jpg",
    "categories": ["역사·문화", "체험·교육"],
    "categories_en": ["History", "Education"],
    "categories_zh": ["历史·文化", "体验·教育"],
    "categories_ja": ["歴史・文化", "体験・教育"],
    "recommendFor": ["가족", "혼자"],
    "address": "금천구 금하로24길 6, 6층",
    "address_en": "6th Fl, 6 Geumha-ro 24-gil, Geumcheon-gu",
    "address_zh": "衿川区 衿河路24路 6, 6楼",
    "address_ja": "衿川区 衿河路24ギル 6, 6階",
    "hours": "평일 09:00~18:00 / 토 09:00~14:30 / 일요일 휴무",
    "hours_en": "Weekdays 09:00-18:00 / Sat 09:00-14:30 / Closed Sundays",
    "hours_zh": "工作日 09:00~18:00 / 周六 09:00~14:30 / 周日休息",
    "hours_ja": "平日 09:00〜18:00 / 土 09:00〜14:30 / 日曜定休",
    "closed_note": "일요일 휴무",
    "fee": "무료",
    "fee_en": "Free",
    "fee_zh": "免费",
    "fee_ja": "無料",
    "transit": "인근 버스 이용",
    "transit_en": "Use nearby buses",
    "transit_zh": "利用附近巴士",
    "transit_ja": "近隣のバスを利用",
    "duration": "1~2시간",
    "duration_en": "1~2 hours",
    "duration_zh": "1~2小时",
    "duration_ja": "1〜2時間",
    "highlights": ["정조대왕 1795년 유숙지","디지털 환어행렬도·시흥행궁 모형","수령 886년 은행나무 3그루","해설 프로그램 운영"],
    "highlights_en": ["King Jeongjo's 1795 lodging", "Digital Procession Map & Siheung Haenggung Model", "Three 886-year-old Ginkgo trees", "Commentary Program"],
    "highlights_zh": ["正祖大王1795年宿营地", "数字还原行列图·始兴行宫模型", "3棵树龄886年的银杏树", "运营解说程序"],
    "highlights_ja": ["正祖大王1795年宿泊地", "デジタル還御行列図・始興行宮模型", "樹齢886年の銀杏の木3本", "解説プログラム運営"],
    "story": "1795년(을묘년) 정조대왕이 화성 행차 시 유일하게 머문 숙소였던 시흥행궁. 역사적 기록에 남아있는 수령 886년 은행나무 3그루도 함께 만날 수 있다.",
    "story_en": "Siheung Haenggung was the only lodging where King Jeongjo stayed during his 1795 visit to Hwaseong. You can also see three 886-year-old ginkgo trees recorded in history.",
    "story_zh": "1795年（乙卯年）正祖大王前往华成出巡时唯一停留过的住所——始兴行宫。还可以见到历史记录中留存的3棵树龄886年的银杏树。",
    "story_ja": "1795年(乙卯年)正祖大王が華成行次の際に唯一滞在した宿泊施設であった始興行宮。歴史的記録に残っている樹齢886年の銀杏の木3本も一緒に見ることができます。",
    "lat": 37.45118,
    "lng": 126.908207
  },
  {
    "id": 7,
    "name": "금천폭포공원",
    "name_en": "Geumcheon Waterfall Park",
    "name_zh": "金川瀑布公园",
    "name_ja": "金川滝公園",
    "image": "/spot7.jpg",
    "categories": ["자연·산책", "야경"],
    "categories_en": ["Nature", "Night View"],
    "categories_zh": ["自然·散步", "夜景"],
    "categories_ja": ["自然・散策", "夜景"],
    "recommendFor": ["연인", "친구"],
    "address": "금천구 시흥대로 인근",
    "address_en": "Near Siheung-daero, Geumcheon-gu",
    "address_zh": "衿川区 始兴大路附近",
    "address_ja": "衿川区 始興大路付近",
    "hours": "24시간",
    "hours_en": "24 hours",
    "hours_zh": "24小时",
    "hours_ja": "24時間",
    "fee": "무료",
    "fee_en": "Free",
    "fee_zh": "免费",
    "fee_ja": "無料",
    "transit": "인근 버스 이용 (금천폭포공원 정류장)",
    "transit_en": "Use nearby buses (Geumcheon Waterfall Park stop)",
    "transit_zh": "利用附近巴士 (金川瀑布公园站)",
    "transit_ja": "近隣のバスを利用 (衿川滝公園停留所)",
    "duration": "1~2시간",
    "duration_en": "1~2 hours",
    "duration_zh": "1~2小时",
    "duration_ja": "1〜2時間",
    "highlights": ["칼바위 형상화 인공폭포","3개 물줄기 (가산동·독산동·시흥동 상징)","산책길","여름 물놀이 시설"],
    "highlights_en": ["Artificial Waterfall shaped like Kalbawi", "3 streams (Symbolizing Gasan, Doksan, Siheung)", "Trail", "Summer Water Play Facility"],
    "highlights_zh": ["以刀岩为原型的入工瀑布", "3条水流 (象征加山洞·秃山洞·始兴洞)", "散步道", "夏季戏水设施"],
    "highlights_ja": ["カルバウィを形象化した人工滝", "3つの水流 (加山・禿山・始興を象徴)", "散策路", "夏の水遊び施設"],
    "story": "호암산의 명물 칼바위를 형상화한 폭포. 3개의 물줄기는 금천구 가산동·독산동·시흥동을 상징하며, 서울 서남권의 관문에 자리하고 있다.",
    "story_en": "A waterfall shaped like the famous Kalbawi rock of Hoamsan. Its three streams symbolize the three neighborhoods of Geumcheon-gu.",
    "story_zh": "以虎岩山的名胜刀岩为原型建造的瀑布。3条水流象征着衿川区的加山洞、秃山洞、始兴洞，位于首尔西南地区的关口。",
    "story_ja": "虎岩山の名物カルバウィを形象化した滝。3つの水流は衿川区の加山洞・禿山洞・始興洞を象徴しており、ソウル南西圏の玄関口に位置しています。",
    "lat": 37.446759,
    "lng": 126.904084
  },
  {
    "id": 8,
    "name": "금천뮤지컬센터",
    "name_en": "Geumcheon Musical Center",
    "name_zh": "金川音乐剧中心",
    "name_ja": "金川ミュージカルセンター",
    "image": "/spot8.jpg",
    "categories": ["예술·공연", "체험·교육"],
    "categories_en": ["Arts", "Education"],
    "categories_zh": ["艺术·演出", "体验·教育"],
    "categories_ja": ["芸術・公演", "体験・教育"],
    "recommendFor": ["연인", "친구", "가족"],
    "address": "금천구 시흥대로115길 48",
    "address_en": "48 Siheung-daero 115-gil, Geumcheon-gu",
    "address_zh": "衿川区 始兴大路115路 48",
    "address_ja": "衿川区 始興大路115ギル 48",
    "hours": "공연장 09:00~22:00 / 연습실 09:00~21:00 (공휴일 제외)",
    "hours_en": "Hall 09:00-22:00 / Studios 09:00-21:00 (Excl. Holidays)",
    "hours_zh": "演出场 09:00~22:00 / 练习室 09:00~21:00 (公休日除外)",
    "hours_ja": "ホール 09:00〜22:00 / 練習室 09:00〜21:00 (公休日除く)",
    "fee": "공연에 따라 상이 (교육 프로그램 무료)",
    "fee_en": "Varies by performance (Edu programs free)",
    "fee_zh": "根据演出而异 (教育项目免费)",
    "fee_ja": "公演により異なる (教育プログラムは無料)",
    "transit": "1호선 독산역 1번출구 도보 13분",
    "transit_en": "Line 1 Doksan Stn Exit 1, 13 min walk",
    "transit_zh": "1号线 秃山站 1号出口 步行13分钟",
    "transit_ja": "1号線 禿山駅 1番出口 徒歩13分",
    "duration": "2~3시간 (공연 관람 시)",
    "duration_en": "2~3 hours (for performance)",
    "duration_zh": "2~3小时 (观看演出时)",
    "duration_ja": "2〜3時間 (公演観覧時)",
    "highlights": ["국내 유일 뮤지컬 특화 전문시설","197석 공연장","대연습실·영상 스튜디오","청소년 뮤지컬 교육"],
    "highlights_en": ["Only specialized musical facility in Korea", "197-seat Theater", "Large Studios & Video Studio", "Youth Musical Education"],
    "highlights_zh": ["国内唯一的音乐剧特化专门设施", "197座演出场", "大练习室·影像工作室", "青少年音乐剧教育"],
    "highlights_ja": ["韓国唯一のミュージカル特化専門施設", "197席のホール", "大練習室・映像スタジオ", "青少年ミュージカル教育"],
    "story": "2021년 개관한 공공기관 최초의 뮤지컬 특화 전문시설. 교육·제작·공연이 한 공간에서 이루어지며, 공연 일정은 금천문화재단(gcfac.or.kr)에서 확인할 수 있다.",
    "story_en": "Opened in 2021 as the first public musical specialty facility. Education, production, and performance all happen in one space.",
    "story_zh": "2021年开馆的公共机构首个音乐剧特化专门设施。教育、制作、演出在同一空间进行，演出日程可在衿川文化财团(gcfac.or.kr)查询。",
    "story_ja": "2021年に開館した公共機関初のミュージカル特化専門施設。教育・制作・公演がひとつの空間で行われ、公演日程は衿川文化財団(gcfac.or.kr)で確認できます。",
    "lat": 37.468991,
    "lng": 126.893848
  },
  {
    "id": 9,
    "name": "서서울미술관",
    "name_en": "West Seoul Museum of Art",
    "name_zh": "西首尔美术馆",
    "name_ja": "西ソウル美術館",
    "image": "/spot9.jpg",
    "categories": ["예술·공연", "역사·문화"],
    "categories_en": ["Arts", "History"],
    "categories_zh": ["艺术·演出", "历史·文化"],
    "categories_ja": ["芸術・公演", "歴史・文化"],
    "recommendFor": ["연인", "혼자"],
    "address": "금천구 시흥대로79길 65 (금나래중앙공원)",
    "address_en": "65 Siheung-daero 79-gil, Geumcheon-gu (Geumnarae Park)",
    "address_zh": "衿川区 始兴大路79路 65 (金娜莱中央公园)",
    "address_ja": "衿川区 始興大路79ギル 65 (クムナレ中央公園)",
    "hours": "화~금 10:00~20:00 / 토·일·공휴일 10:00~19:00 / 월요일 휴관",
    "hours_en": "Tue-Fri 10:00-20:00 / Sat-Sun 10:00-19:00 / Closed Mondays",
    "hours_zh": "周二~周五 10:00~20:00 / 周六·周日·公休日 10:00~19:00 / 周一闭馆",
    "hours_ja": "火〜金 10:00〜20:00 / 土・日・祝 10:00〜19:00 / 月曜休館",
    "closed_note": "월요일 휴관",
    "fee": "무료 (특별전 유료 가능)",
    "fee_en": "Free (Exhibitions may charge fee)",
    "fee_zh": "免费 (特别展可能收费)",
    "fee_ja": "無料 (特別展は有料の場合あり)",
    "transit": "1호선 금천구청역 1번출구",
    "transit_en": "Line 1 Geumcheon-gu Office Stn Exit 1",
    "transit_zh": "1号线 衿川区厅站 1号出口",
    "transit_ja": "1号線 衿川区庁駅 1番出口",
    "duration": "1~2시간",
    "duration_en": "1~2 hours",
    "duration_zh": "1~2小时",
    "duration_ja": "1〜2時間",
    "highlights": ["2026년 3월 12일 개관","서울 서남권 최초 공립미술관","뉴미디어 특화 미술관","김찬중 건축가 설계 스트리트형 건물"],
    "highlights_en": ["Opened Mar 12, 2026", "First public art museum in SW Seoul", "New Media Specialized", "Designed by Architect Chanjoong Kim"],
    "highlights_zh": ["2026年3月12日开馆", "首尔西南地区首个公立美术馆", "新媒体特化美术馆", "金灿中建筑师设计的街道型建筑"],
    "highlights_ja": ["2026年3月12日開館", "ソウル南西圏初の公立美術館", "ニューメディア特化美術館", "キム・チャンジュン建築家設計のストリート型建物"],
    "story": "2026년 3월 개관한 서울시립미술관의 8번째 분관. 과거 구로공단에서 IT·디지털 산업단지로 변모한 금천구의 정체성을 담은 뉴미디어 특화 공립미술관이다.",
    "story_en": "The 8th branch of Seoul Museum of Art, opened in March 2026. A public art museum specialized in new media, reflecting the identity of Geumcheon-gu.",
    "story_zh": "2026年3月开馆的首尔市立美术馆第8个分馆。包含从过去的九老工团转变为IT·数字产业园区的衿川区身份的新媒体特化公立美术馆。",
    "story_ja": "2026年3月に開館したソウル市立美術館の8番目の分館。過去の九老工団からIT・デジタル産業団地へと変貌した衿川区のアイデンティティを込めたニューメディア特化の公立美術館です。",
    "lat": 37.4578,
    "lng": 126.8958
  }
];
